func foo() {
  print(y);   /* generates an ErrorType.NAME_ERROR */
}

func bar() {
  y = 10;
  x = foo;    /* y is not captured by this assignment */
}

func main() {
  x = nil;
  bar();
  x();
}

/*
*OUT*
ErrorType.NAME_ERROR
*OUT*
*/